/:
  controller: Main
  action: home
  role: 
    - none

/contact:
  controller: Main
  action: contact
  role: 
    - none

/login:
  controller: user
  action: login
  role: 
    - none

/logout:
  controller: user
  action: logout
  role: 
    - none

/register:
  controller: user
  action: register
  role: 
    - none

/activation:
  controller: user
  action: activation
  role: 
    - none

/forget:
  controller: user
  action: pwdforget
  role: 
    - none

/Newpage:
  controller: page
  action: NewPage

/readPage:
  controller: page
  action: readPage

/list:
  controller: page
  action: displayAllPages
  role:
    - admin

/reset-pwd:
  controller: user
  action: resetpassword
  role: 
    - none

/profile:
  controller: user
  action: showprofile
  role:
    - none

/profile-editpassword:
  controller: user
  action: editpasswordprofile
  role:
    - none

/mail:
  controller: user
  action: sendmail
  role: 
    - none

/dashboard:
  controller: admin
  action: dashboard
  role:
    - admin

/users:
  controller: user
  action: users
  role:
    - admin

/user-remove:
  controller: user
  action: removeUser
  role:
    - admin

/user:
  controller: user
  action: showUser
  role:
    - admin

/user-edit:
  controller: user
  action: editUser
  role:
    - admin

/comments:
  controller: comment
  action: comments
  role:
    - admin

/comment-remove:
  controller: comment
  action: removeComment
  role:
    - admin

/comment-add:
  controller: comment
  action: addComment
  role:
    - user
    - admin

/comment-activate:
  controller: comment
  action: activateComment
  role:
    - admin

/testcommentpage:
  controller: main
  action: samplepage
  role:
    - none
