/:
  controller: Main
  action: home
  role: 
    - none

/contact:
  controller: Main
  action: contact
  role: 
    - none

/login:
  controller: user
  action: login
  role: 
    - none

/logout:
  controller: user
  action: logout
  role: 
    - none

/register:
  controller: user
  action: register
  role: 
    - none

/activation:
  controller: user
  action: activation
  role: 
    - none

/forget:
  controller: user
  action: pwdforget
  role: 
    - none

/newpage:
  controller: page
  action: newpage
  role: 
    - none

/readpage:
  controller: page
  action: readpage
  role: 
    - none

/editpage:
  controller: page
  action: editpage
  role: 
    - none

  


/list:
  controller: page
  action: displayAllPages
  role:
    - admin

/reset-pwd:
  controller: user
  action: resetpassword
  role: 
    - none

/profile:
  controller: user
  action: showprofile
  role:
    - none

/profile-editpassword:
  controller: user
  action: editpasswordprofile
  role:
    - none

/mail:
  controller: user
  action: sendmail
  role: 
    - none

/dashboard:
  controller: admin
  action: dashboard
  role:
    - admin

/users:
  controller: user
  action: users
  role:
    - admin

/user-remove:
  controller: user
  action: removeUser
  role:
    - admin

/user:
  controller: user
  action: showUser
  role:
    - admin

/user-edit:
  controller: user
  action: editUser
  role:
    - admin